export const COMPANY = {
  name: "Saurabh Infosys",
  tagline: "AI-first software development studio",
  location: "Ahmedabad, Gujarat, India",
  website: "saurabhinfosys.com",
  email: "info@saurabhinfosys.com",
  phone: "+91 87350 01217",
  whatsapp: "918735001217",
  stats: {
    clients: "80+",
    projects: "50+",
    years: "4+",
    saasProducts: "3",
    clutchRating: "4.9",
    clutchReviews: "33",
  },
};

export const SERVICES = [
  {
    slug: "ai-agents",
    title: "AI Automation Services",
    shortTitle: "AI Automation",
    icon: "🤖",
    description:
      "Agentic AI & GenAI services — WhatsApp bots, RAG systems, voice agents, and AI integration into your existing business software. Real business impact, delivered in weeks.",
    features: [
      "Agentic AI & GenAI Development",
      "WhatsApp Business Automation",
      "AI Integration into Existing Systems",
      "RAG Knowledge Bases",
      "Voice Agents (Hindi/English)",
      "CRM & API AI Integration",
    ],
    heroDesc:
      "We deliver AI automation, Agentic AI, and GenAI services for Indian businesses — automating workflows, integrating AI into existing software, and building intelligent agents that run 24/7.",
    useCases: [
      { title: "Agentic AI & Automation", desc: "Automate customer support, lead qualification, and repetitive workflows via AI agents." },
      { title: "AI Integration", desc: "Integrate GPT-4o, RAG, and GenAI into your existing CRM, ERP, or business software." },
      { title: "Voice Agents", desc: "AI phone agents that handle inbound calls in Hindi and English." },
    ],
  },
  {
    slug: "vibe-coding",
    title: "Vibe Coding / AI-Enabled Apps",
    shortTitle: "Vibe Coding",
    icon: "⚡",
    description:
      "India's leading vibe coding studio. Ship AI-enabled apps and production-ready MVPs in 2 weeks, not 2 months.",
    features: [
      "2-Week AI-Enabled App Delivery",
      "Built-in AI Features (Chat, Recommendations)",
      "Next.js / React / Flutter",
      "Supabase / Firebase Backend",
      "Payment Integration",
      "Admin Dashboard Included",
    ],
    heroDesc:
      "Using vibe coding and AI-accelerated development, we build AI-enabled apps and MVPs in 2 weeks at a fraction of traditional cost. Validate your idea fast.",
    useCases: [
      { title: "AI-Enabled Apps", desc: "Apps with built-in AI — smart search, chatbots, recommendations, and automation." },
      { title: "Startup MVPs", desc: "Validate your idea with a production-ready app in 2 weeks." },
      { title: "Internal Tools", desc: "Replace spreadsheets with AI-powered dashboards and automation." },
    ],
  },
  {
    slug: "flutter",
    title: "Flutter Mobile Apps",
    shortTitle: "Flutter Apps",
    icon: "📱",
    description:
      "Cross-platform iOS & Android apps with a single codebase. Live on Play Store & App Store.",
    features: [
      "iOS + Android from One Codebase",
      "Play Store & App Store Deployment",
      "Firebase / REST API Backend",
      "Push Notifications",
      "Offline-First Architecture",
      "App Store Optimization",
    ],
    heroDesc:
      "We've shipped Flutter apps used by 30,000+ customers across 20 countries. From fitness apps to dental lab management — we build it right.",
    useCases: [
      { title: "Consumer Apps", desc: "B2C apps with beautiful UI and seamless UX for iOS and Android." },
      { title: "Business Apps", desc: "Field staff, delivery, or client-facing apps with real-time data." },
      { title: "App Revamps", desc: "Migrate your legacy native app to a modern Flutter codebase." },
    ],
  },
  {
    slug: "gps",
    title: "GPS & Fleet Management",
    shortTitle: "GPS & Fleet",
    icon: "🗺️",
    description:
      "Real-time vehicle tracking, route optimization, and fleet analytics for logistics businesses.",
    features: [
      "Real-Time GPS Tracking",
      "Live Map Dashboard",
      "Driver Behaviour Analytics",
      "Route Optimization",
      "Fuel & Maintenance Logs",
      "Alerts & Notifications",
    ],
    heroDesc:
      "Custom GPS and fleet management systems built for logistics companies, transport operators, and delivery fleets.",
    useCases: [
      { title: "Transport Companies", desc: "Track your entire fleet live and reduce fuel costs with route optimization." },
      { title: "Delivery Fleets", desc: "Monitor last-mile deliveries and share live tracking links with customers." },
      { title: "School Transport", desc: "Parent-facing apps with live bus tracking and arrival notifications." },
    ],
  },
  {
    slug: "saas",
    title: "SaaS Platform Development",
    shortTitle: "SaaS Dev",
    icon: "☁️",
    description:
      "End-to-end SaaS platforms with multi-tenancy, billing, and admin dashboards — we built 3 of our own.",
    features: [
      "Multi-Tenant Architecture",
      "Subscription Billing (Razorpay/Stripe)",
      "Role-Based Access Control",
      "Admin Super Dashboard",
      "API-First Design",
      "Scalable Cloud Infrastructure",
    ],
    heroDesc:
      "We don't just build SaaS — we run our own. SSMS, MySociety, and MySampark are live products we built and operate, giving us real-world SaaS expertise.",
    useCases: [
      { title: "Vertical SaaS", desc: "Industry-specific SaaS for education, real estate, healthcare, and more." },
      { title: "Marketplace Platforms", desc: "Multi-vendor platforms with seller dashboards and buyer apps." },
      { title: "Internal SaaS", desc: "White-label platforms for enterprises with custom branding." },
    ],
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing Tools",
    shortTitle: "Marketing Tech",
    icon: "📣",
    description:
      "Bulk WhatsApp, SMS, and email marketing tools. We built MySampark — our own marketing SaaS.",
    features: [
      "Bulk WhatsApp Campaigns",
      "SMS Marketing Automation",
      "Email Campaign Builder",
      "Contact List Management",
      "Campaign Analytics",
      "API Access for Developers",
    ],
    heroDesc:
      "Built on our own MySampark platform, we create digital marketing tools that help SMBs reach thousands of customers at minimal cost.",
    useCases: [
      { title: "SMB Campaigns", desc: "Reach your customer base via WhatsApp, SMS, and email in bulk." },
      { title: "Reseller Platforms", desc: "White-label marketing platforms for digital marketing agencies." },
      { title: "Integrations", desc: "Connect your CRM or e-commerce store to automated campaigns." },
    ],
  },
];

export const PRODUCTS = [
  {
    slug: "ssms",
    name: "SSMS",
    fullName: "School Management System",
    url: "https://sms.saurabhinfosys.com",
    tagline: "Complete school operations in one platform",
    price: "₹999/year",
    priceNote: "Launch price — limited time",
    color: "from-blue-600 to-blue-800",
    accentColor: "blue",
    description:
      "A comprehensive school management system covering admissions, attendance, fees, reports, and parent communication.",
    features: [
      "Student Admissions & Profiles",
      "Attendance Management",
      "Fee Collection & Receipts",
      "Exam Results & Report Cards",
      "Parent Communication Portal",
      "Staff & HR Management",
      "Transport Tracking",
      "WhatsApp Notifications",
    ],
    targetUsers: ["Private Schools", "Coaching Institutes", "Tutoring Centers"],
  },
  {
    slug: "mysociety",
    name: "MySociety",
    fullName: "Society Management System",
    url: "https://mysociety.saurabhinfosys.com",
    tagline: "Modern society management for housing complexes",
    price: "₹5/flat/month",
    priceNote: "Per flat per month, billed annually",
    color: "from-green-600 to-green-800",
    accentColor: "green",
    description:
      "End-to-end society management covering maintenance collection, visitor logs, complaints, and resident communication.",
    features: [
      "Maintenance Fee Collection",
      "Visitor Gate Management",
      "Complaint & Helpdesk System",
      "Notice Board & Announcements",
      "Resident Directory",
      "Parking Management",
      "Vendor & AMC Tracking",
      "WhatsApp Alerts",
    ],
    targetUsers: ["Housing Societies", "Apartment Complexes", "Gated Communities"],
  },
  {
    slug: "mysampark",
    name: "MySampark",
    fullName: "Digital Marketing Platform",
    url: "https://mysampark.com",
    tagline: "Reach thousands via WhatsApp, SMS & Email",
    price: "Pay-per-use",
    priceNote: "No monthly fee — pay only for what you send",
    color: "from-purple-600 to-purple-800",
    accentColor: "purple",
    description:
      "A bulk communication platform for WhatsApp, SMS, and email campaigns — built for Indian SMBs and marketing agencies.",
    features: [
      "Bulk WhatsApp Messaging",
      "SMS Campaign Builder",
      "Email Marketing",
      "Contact List Management",
      "Campaign Analytics Dashboard",
      "Template Library",
      "API Access",
      "Reseller Program",
    ],
    targetUsers: ["Marketing Agencies", "SMBs", "E-commerce Businesses"],
  },
];

export const CLIENTS = [
  {
    name: "Modern Dental Lab",
    country: "Hong Kong",
    flag: "🇭🇰",
    description: "Flutter mobile app serving 30,000+ customers across 20 countries.",
    category: "Healthcare",
    highlight: "30K+ customers, 20 countries",
  },
  {
    name: "ATCC Australia",
    country: "Australia",
    flag: "🇦🇺",
    description: "Transport compliance software for a 25-year-old industry leader.",
    category: "Transport",
    highlight: "25-year company",
  },
  {
    name: "Curvd by CapriCurves",
    country: "USA",
    flag: "🇺🇸",
    description: "Fitness app live on Play Store and App Store.",
    category: "Health & Fitness",
    highlight: "Live on both stores",
  },
  {
    name: "TPI Veterans NSW",
    country: "Australia",
    flag: "🇦🇺",
    description: "Website and member portal for veterans association.",
    category: "Government / NGO",
    highlight: "Veterans association",
  },
  {
    name: "Digital Retail Display",
    country: "UK",
    flag: "🇬🇧",
    description: "Android TV digital signage app with cloud admin dashboard.",
    category: "Retail Tech",
    highlight: "Digital signage",
  },
];

export const PORTFOLIO_PROJECTS = [
  // AI
  { id: 1,  title: "AI Assist",            category: "AI",         description: "AI-powered educational platform with live tests, instant results, and personalised study material for students.", tech: ["Flutter", "OpenAI", "Firebase"] },
  { id: 2,  title: "Banigi AI",            category: "AI",         description: "AI-driven business intelligence platform with smart analytics, automated reporting, and conversational insights.", tech: ["React", "Python", "OpenAI"] },
  { id: 3,  title: "Learning",             category: "Education",  description: "Personalised e-learning app with adaptive content delivery, progress tracking, and quiz modules.", tech: ["Flutter", "Firebase", "Node.js"] },
  { id: 4,  title: "Smart Theory Test",    category: "Education",  description: "UK driving theory test preparation app with the largest categorised real-question bank, updated to current regulations.", tech: ["Next.js", "PostgreSQL", "Tailwind"] },
  { id: 5,  title: "Meow Cademy",          category: "Education",  description: "Online learning platform for pet care, cat training, and animal behaviour — courses with video and quizzes.", tech: ["React", "Supabase", "Stripe"] },
  { id: 6,  title: "MacroMate",            category: "Health",     description: "Nutrition balance companion app with personalised dietary guides, macro tracking, and healthy eating insights.", tech: ["Flutter", "Firebase", "REST API"] },
  { id: 7,  title: "Fit Gate",             category: "Health",     description: "Gym and fitness centre access management platform with member check-ins, billing, and class scheduling.", tech: ["Flutter", "Node.js", "PostgreSQL"] },
  { id: 8,  title: "Sleepz",              category: "Health",     description: "Sleep quality tracking and improvement app with AI-powered coaching, sleep score analysis, and habit nudges.", tech: ["Flutter", "Firebase", "ML Kit"] },
  { id: 9,  title: "Cookpedia",           category: "Health",     description: "Recipe discovery and meal planning app with ingredient-based search, nutrition info, and weekly meal plans.", tech: ["React Native", "Node.js", "MongoDB"] },
  { id: 10, title: "EV Connect",          category: "Transport",  description: "EV charging station finder with real-time availability updates, navigation, and charging session management.", tech: ["Flutter", "Node.js", "Google Maps"] },
  { id: 11, title: "Commute",             category: "Transport",  description: "Ride-sharing expense tracker — effortlessly track who owes whom for shared car journeys across groups and co-workers.", tech: ["Flutter", "Firebase", "Razorpay"] },
  { id: 12, title: "Quick Delivery",      category: "Transport",  description: "On-demand last-mile delivery platform with real-time tracking, driver app, and customer notifications.", tech: ["Flutter", "Node.js", "Google Maps"] },
  { id: 13, title: "Loadbase",            category: "Transport",  description: "Load management and freight booking platform connecting shippers with truck owners across India.", tech: ["React", "Node.js", "PostgreSQL"] },
  { id: 14, title: "TTAC",               category: "Transport",  description: "Transport tracking and compliance management system for fleet operators with driver logs and route analytics.", tech: ["React", "Node.js", "PostgreSQL"] },
  { id: 15, title: "VIN Solutions",      category: "Transport",  description: "Vehicle identification and dealership management platform with VIN lookup, inventory, and sales tracking.", tech: ["Next.js", "PostgreSQL", "REST API"] },
  { id: 16, title: "Barber Plus",         category: "Gig",        description: "Barber shop booking and appointment management app with stylist profiles, reviews, and online payments.", tech: ["Flutter", "Firebase", "Stripe"] },
  { id: 17, title: "Walk Dogs",           category: "Gig",        description: "Dog walking and pet care booking platform connecting pet owners with trusted local walkers.", tech: ["Flutter", "Firebase", "Google Maps"] },
  { id: 18, title: "InstaJob",            category: "Gig",        description: "Instant job matching platform connecting blue-collar workers with short-term and daily wage opportunities.", tech: ["React Native", "Node.js", "PostgreSQL"] },
  { id: 19, title: "Helping Hands",       category: "NGO",        description: "Volunteer coordination and community support platform for NGOs — task assignments, tracking, and impact reporting.", tech: ["React", "Firebase", "Tailwind"] },
  { id: 20, title: "Pots",               category: "Fintech",    description: "Savings pot and micro-investment platform allowing users to set savings goals and automate contributions.", tech: ["Flutter", "Node.js", "Razorpay"] },
  { id: 21, title: "Volest",             category: "Fintech",    description: "Investment portfolio tracker with real-time market data, asset allocation analytics, and performance reports.", tech: ["React", "Node.js", "Chart.js"] },
  { id: 22, title: "Retirement Planning", category: "Fintech",    description: "Retirement savings calculator and financial planning tool with scenario modelling and SIP recommendations.", tech: ["React", "Node.js", "PostgreSQL"] },
  { id: 23, title: "Assets Management",   category: "Fintech",    description: "Digital asset tracking and management system for businesses — equipment, inventory, and depreciation tracking.", tech: ["Next.js", "PostgreSQL", "REST API"] },
  { id: 24, title: "Subrate",            category: "SaaS",       description: "Subscription management and recurring billing platform with dunning automation, analytics, and multi-currency support.", tech: ["Next.js", "Supabase", "Stripe"] },
  { id: 25, title: "Review",             category: "SaaS",       description: "Customer review and feedback management platform with automated collection, sentiment analysis, and public widgets.", tech: ["React", "Node.js", "PostgreSQL"] },
  { id: 26, title: "WMS",               category: "Custom Dev",  description: "Warehouse management system with barcode scanning, inventory tracking, pick-and-pack workflows, and dispatch management.", tech: ["React", "Node.js", "PostgreSQL"] },
  { id: 27, title: "Barcode Scanner",    category: "Custom Dev",  description: "Mobile barcode scanning solution for retail and warehouse inventory management with real-time stock updates.", tech: ["Flutter", "REST API", "Firebase"] },
  { id: 28, title: "Formwork",           category: "Custom Dev",  description: "No-code digital form builder with conditional logic, file uploads, e-signatures, and submission analytics.", tech: ["React", "Node.js", "AWS S3"] },
  { id: 29, title: "Doodler",           category: "Custom Dev",  description: "Creative digital drawing and sketching application with layers, brushes, and cloud sync for artists.", tech: ["Flutter", "Firebase", "Canvas API"] },
  { id: 30, title: "Knock Knock",        category: "Custom Dev",  description: "Smart door access and visitor management app for gated communities with intercom and digital keys.", tech: ["Flutter", "Firebase", "IoT API"] },
  { id: 31, title: "Panapa",            category: "Custom Dev",  description: "Social connection and local networking platform built for community groups and neighbourhood engagement.", tech: ["React Native", "Node.js", "PostgreSQL"] },
  { id: 32, title: "Riiicycle",         category: "Custom Dev",  description: "Sustainable recycling marketplace and rewards app — users earn points for recycling pickups and eco actions.", tech: ["Flutter", "Firebase", "Node.js"] },
  { id: 33, title: "Changa Po",         category: "Custom Dev",  description: "Marketplace platform for local services with provider onboarding, booking flow, and in-app chat.", tech: ["React Native", "Node.js", "Stripe"] },
  { id: 34, title: "Moyabet",           category: "Custom Dev",  description: "Sports analytics and mobile betting companion app with live scores, predictions, and community discussions.", tech: ["Flutter", "Node.js", "REST API"] },
  { id: 35, title: "CH90",              category: "Custom Dev",  description: "Custom hospitality management system for hotels — reservations, housekeeping, billing, and guest communication.", tech: ["React", "Node.js", "PostgreSQL"] },
  { id: 36, title: "EPAV",              category: "Custom Dev",  description: "Enterprise process automation and visualisation platform with workflow builder, approvals, and reporting dashboards.", tech: ["React", "Node.js", "PostgreSQL"] },
  { id: 37, title: "VTM",              category: "Custom Dev",  description: "Vehicle tracking and management solution with live GPS, maintenance scheduling, and driver performance analytics.", tech: ["React", "Node.js", "WebSockets"] },
  { id: 38, title: "FLPL",              category: "Custom Dev",  description: "Custom logistics and fleet planning platform with route optimisation, load matching, and billing integration.", tech: ["React", "Node.js", "Maps API"] },
];

export const PORTFOLIO_CATEGORIES = [
  "All", "AI", "Education", "Health", "Transport", "Gig", "Fintech", "SaaS", "NGO", "Custom Dev"
];

export const BLOG_POSTS = [
  // New AI-focused posts (written by us)
  {
    slug: "what-is-vibe-coding",
    title: "What is Vibe Coding? How AI is Changing Software Development in 2025",
    category: "AI Development",
    date: "2026-04-10",
    readTime: "6 min read",
    excerpt: "Vibe coding is the AI-accelerated development method taking the startup world by storm. Here's what it means, why it matters, and how Saurabh Infosys uses it to ship MVPs in 2 weeks.",
    isNew: true,
  },
  {
    slug: "top-ai-automation-use-cases-india",
    title: "Top 10 AI Automation Use Cases for Indian Businesses in 2025",
    category: "AI Automation",
    date: "2026-04-05",
    readTime: "8 min read",
    excerpt: "From WhatsApp bots to invoice processing — discover the 10 highest-ROI AI automation use cases transforming Indian SMBs and enterprises right now.",
    isNew: true,
  },
  {
    slug: "how-to-integrate-ai-existing-software",
    title: "How to Integrate AI into Your Existing Business Software",
    category: "AI Integration",
    date: "2026-03-28",
    readTime: "7 min read",
    excerpt: "You don't need to rebuild from scratch. A practical guide to adding AI capabilities — chatbots, recommendations, and automation — to your existing CRM, ERP, or web app.",
    isNew: true,
  },
  {
    slug: "agentic-ai-vs-chatbots",
    title: "Agentic AI vs Traditional Chatbots: What's the Real Difference?",
    category: "AI Automation",
    date: "2026-03-20",
    readTime: "5 min read",
    excerpt: "Traditional chatbots answer questions. Agentic AI takes actions. Here's what that difference means for your business — and why 2025 is the year to upgrade.",
    isNew: true,
  },
  {
    slug: "whatsapp-ai-bot-indian-business",
    title: "Why Every Indian SMB Needs a WhatsApp AI Bot in 2025",
    category: "AI Automation",
    date: "2026-03-12",
    readTime: "6 min read",
    excerpt: "500 million Indians use WhatsApp daily. An AI bot on WhatsApp can handle leads, bookings, and support 24/7 — at a fraction of hiring costs. Here's how to get started.",
    isNew: true,
  },
  {
    slug: "flutter-ai-enabled-apps",
    title: "Building AI-Enabled Mobile Apps with Flutter: A Complete Guide",
    category: "AI Development",
    date: "2026-03-05",
    readTime: "9 min read",
    excerpt: "Flutter + AI is a powerful combo for cross-platform apps. This guide covers integrating OpenAI, on-device ML, and RAG into Flutter apps — with real examples from our portfolio.",
    isNew: true,
  },
  // Real posts from saurabhinfosys.com
  {
    slug: "ai-transforming-web-development-2025",
    title: "How AI is Transforming Modern Web Development in 2025",
    category: "Artificial Intelligence",
    date: "2025-10-27",
    readTime: "7 min read",
    excerpt: "Discover how Artificial Intelligence is revolutionising modern web and app development in 2025 — from automated code generation to intelligent testing.",
    isNew: false,
  },
  {
    slug: "flutter-vs-react-native-2025",
    title: "Flutter vs. React Native: Which is Better for Mobile App Development?",
    category: "Mobile Development",
    date: "2025-07-01",
    readTime: "8 min read",
    excerpt: "An in-depth comparison of Flutter and React Native for mobile app development in 2025 — performance, ecosystem, and when to choose which.",
    isNew: false,
  },
  {
    slug: "future-software-development-emerging-tech",
    title: "The Future of Software Development: Emerging Technologies and Strategies",
    category: "Technology",
    date: "2025-06-20",
    readTime: "6 min read",
    excerpt: "From AI-assisted coding to serverless architectures — the technologies and strategies that will define software development in the next 3 years.",
    isNew: false,
  },
  {
    slug: "why-flutter-2025",
    title: "Why You Should Consider Flutter for Your Next App (2025)",
    category: "Mobile Development",
    date: "2025-04-15",
    readTime: "5 min read",
    excerpt: "Flutter's cross-platform efficiency, fast UI, and growing ecosystem make it one of the best choices for mobile apps in 2025. Here's why.",
    isNew: false,
  },
  {
    slug: "mobile-first-development-2025",
    title: "Why Mobile-First Development Should Be Your Top Priority in 2025",
    category: "Technology",
    date: "2025-06-15",
    readTime: "5 min read",
    excerpt: "With over 60% of web traffic coming from mobile devices, building mobile-first is no longer optional — it's essential for user experience and SEO.",
    isNew: false,
  },
  {
    slug: "pwa-essential-2025",
    title: "Why Progressive Web Apps (PWAs) Are Essential in 2025",
    category: "Technology",
    date: "2025-05-01",
    readTime: "6 min read",
    excerpt: "PWAs combine the best of web and native apps. Discover why leading businesses are adopting PWAs to improve engagement and cut app development costs.",
    isNew: false,
  },
];

export const TESTIMONIALS = [
  {
    name: "James Wilson",
    role: "Director, Modern Dental Lab",
    country: "Hong Kong 🇭🇰",
    text: "Saurabh Infosys built our Flutter app that now serves 30,000+ customers across 20 countries. Exceptional quality and communication throughout.",
    rating: 5,
  },
  {
    name: "Michael Thompson",
    role: "CEO, ATCC Australia",
    country: "Australia 🇦🇺",
    text: "Professional team with deep technical knowledge. They understood our compliance requirements perfectly and delivered exactly what we needed.",
    rating: 5,
  },
  {
    name: "Sarah Capri",
    role: "Founder, Curvd by CapriCurves",
    country: "USA 🇺🇸",
    text: "Our fitness app is now live on both the App Store and Play Store. The team was responsive, creative, and delivered ahead of schedule.",
    rating: 5,
  },
  {
    name: "Rahul Sharma",
    role: "Principal, Delhi Public School",
    country: "India 🇮🇳",
    text: "SSMS transformed how we manage our school. From fee collection to parent communication — everything is seamless now.",
    rating: 5,
  },
  {
    name: "Amit Patel",
    role: "Secretary, Shivalik Heights Society",
    country: "India 🇮🇳",
    text: "MySociety has made managing our 200-flat complex a breeze. Maintenance collection alone has saved us 10 hours per month.",
    rating: 5,
  },
];
